name: opensense_sandbox
dependencies:
  - r-base=4.1.3
  - r-essentials  
  - r-ggplot2
  - r-ncdf4
  - r-data.table
  - r-geosphere
  - r-sf
  - r-s2
  - r-TeachingDemos
  - numpy
  - matplotlib    
  - pandas
  - xarray
  - netcdf4    
